/*
- Author: Generated by AI (based on existing PARA Project script)
- Create Time: 2025-08-27
- Description: 将当前笔记的 PARA 属性切换为字符串 "[[∑ 2-Area]]"；若已为该值则删除。
- warning: 文件开头不要放任何非注释文本。
- Version: 1.0
*/

// Obsidian 类型声明（仅用于 TypeScript 编译，运行时由 Obsidian 提供）
declare const app: any;
declare const Notice: any;

// --- 配置项 ---
const paraProperty = "PARA";
const targetValue = "[[∑ 2-Area]]"; // 必须是字符串
// --- END ---

function toggleParaProperty(fm: any) {
    const hasProperty = Object.prototype.hasOwnProperty.call(fm, paraProperty);
    const currentValue = fm[paraProperty];

    if (currentValue === targetValue) {
        delete fm[paraProperty];
        return "removed";
    }

    fm[paraProperty] = targetValue;
    return hasProperty ? "replaced" : "added";
}

function main() {
    const activeFile = app.workspace.getActiveFile();
    if (!activeFile) {
        new Notice("错误：无法找到当前文件。", 5000);
        return;
    }

    const noteName = activeFile.basename;
    app.fileManager.processFrontMatter(activeFile, (fm: any) => {
        try {
            const result = toggleParaProperty(fm);
            if (result === "added") {
                new Notice(`已为笔记 "${noteName}" 添加 PARA: ${targetValue}。`, 1200);
            } else if (result === "replaced") {
                new Notice(`已将笔记 "${noteName}" 的 PARA 替换为 ${targetValue}。`, 1200);
            } else if (result === "removed") {
                new Notice(`已从笔记 "${noteName}" 移除 PARA 属性。`, 1200);
            }
        } catch (e) {
            const errorMessage = `为笔记 "${noteName}" 更新 PARA 时出错: ${(e as Error).message}`;
            new Notice(errorMessage, 5000);
            console.error(errorMessage);
        }
    });
}

export async function invoke() {
    main();
}
