/*
- Author: Generated by AI (based on existing review toggle script)
- Create Time: 2025-08-27
- Description: 该脚本用于为当前笔记切换 PARA 属性为字符串 "[[∑ 1-Project]]"。
-            若 PARA 已等于该值，则删除 PARA 属性；否则将 PARA 设为该字符串（非数组）。
- warning: 这个脚本的最前面，不能放任何文本，frontmatter也不行，不然会被当做模版的一部分插入到笔记中。
- Version: 1.0
*/

// Obsidian 类型声明（仅用于 TypeScript 编译，运行时由 Obsidian 提供）
declare const app: any;
declare const Notice: any;

// --- 配置项 ---
const paraProperty = "PARA";
const targetValue = "[[∑ 1-Project]]"; // 注意：必须是字符串，而不是数组
// --- END ---

function toggleParaProperty(fm: any) {
    const hasProperty = Object.prototype.hasOwnProperty.call(fm, paraProperty);
    const currentValue = fm[paraProperty];

    // 若已为期望值，则删除该属性
    if (currentValue === targetValue) {
        delete fm[paraProperty];
        return "removed";
    }

    // 否则统一设置为字符串 targetValue（覆盖数组或其他类型）
    fm[paraProperty] = targetValue;
    return hasProperty ? "replaced" : "added";
}

function main() {
    const activeFile = app.workspace.getActiveFile();
    if (!activeFile) {
        new Notice("错误：无法找到当前文件。", 5000);
        return;
    }

    const noteName = activeFile.basename;
    app.fileManager.processFrontMatter(activeFile, (fm: any) => {
        try {
            const result = toggleParaProperty(fm);
            if (result === "added") {
                new Notice(`已为笔记 "${noteName}" 添加 PARA: ${targetValue}。`, 1200);
            } else if (result === "replaced") {
                new Notice(`已将笔记 "${noteName}" 的 PARA 替换为 ${targetValue}。`, 1200);
            } else if (result === "removed") {
                new Notice(`已从笔记 "${noteName}" 移除 PARA 属性。`, 1200);
            }
        } catch (e) {
            const errorMessage = `为笔记 "${noteName}" 更新 PARA 时出错: ${(e as Error).message}`;
            new Notice(errorMessage, 5000);
            console.error(errorMessage);
        }
    });
}

// 导出 invoke 函数，供 fix-require-modules 插件调用
export async function invoke() {
    main();
}
